# -*- coding: utf-8 -*-
"""Backend.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QHCaURM8vJIi9V_PKPc4j_3CjJxTXx7S
"""

import json
from typing import Dict, List, Any
import re
from datetime import datetime
#Overall structure
#1. receive patient information one by one
#2. create json file for patient information
#3. pass json file to llm
#4. receive meal plan and aggregate daily procurement
#5. pass back patient meal plan for 7 days
#6. pass back daily procurement at the very end


#0. data structure is in types.ts
#1. receive patient information one by one
def extract_patient_schema(typescript_file: str) -> Dict[str, Any]:
    """
    Extract Patient interface structure from TypeScript file.

    Args:
        typescript_file: Path to the TypeScript file

    Returns:
        Dictionary containing the Patient schema
    """
    with open(typescript_file, 'r') as f:
        content = f.read()

    # Find Patient interface definition
    patient_pattern = r'export interface Patient \{([^}]+)\}'
    match = re.search(patient_pattern, content, re.DOTALL)

    if not match:
        raise ValueError("Patient interface not found in file")

    interface_content = match.group(1)

    # Parse fields
    schema = {}
    field_pattern = r'(\w+):\s*([^;]+);'

    for field_match in re.finditer(field_pattern, interface_content):
        field_name = field_match.group(1).strip()
        field_type = field_match.group(2).strip()
        schema[field_name] = field_type

    return schema


def create_sample_patient(patient_id: str = "P001") -> Dict[str, Any]:
    """
    Create a sample patient object based on the Patient interface.

    Args:
        patient_id: Unique identifier for the patient

    Returns:
        Dictionary containing sample patient data
    """
    return {
        "id": patient_id,
        "name": "John Doe",
        "age": 45,
        "weight": 75.5,
        "height": 175.0,
        "dietaryRestrictions": ["vegetarian", "lactose-free"],
        "allergies": ["peanuts", "shellfish"],
        "medicalConditions": ["diabetes type 2", "hypertension"],
        "calorieTarget": 2000,
        "notes": "Patient prefers Mediterranean-style meals. Morning exercise routine."
    }


def create_multiple_patients(count: int = 3) -> List[Dict[str, Any]]:
    """
    Create multiple sample patients with varied data.

    Args:
        count: Number of sample patients to create

    Returns:
        List of patient dictionaries
    """
    patients = [
        {
            "id": "P001",
            "name": "John Doe",
            "age": 45,
            "weight": 75.5,
            "height": 175.0,
            "dietaryRestrictions": ["vegetarian", "lactose-free"],
            "allergies": ["peanuts", "shellfish"],
            "medicalConditions": ["diabetes type 2", "hypertension"],
            "calorieTarget": 2000,
            "notes": "Patient prefers Mediterranean-style meals. Morning exercise routine."
        },
        {
            "id": "P002",
            "name": "Jane Smith",
            "age": 32,
            "weight": 62.0,
            "height": 165.0,
            "dietaryRestrictions": ["gluten-free"],
            "allergies": ["dairy"],
            "medicalConditions": ["celiac disease"],
            "calorieTarget": 1800,
            "notes": "Athlete training for marathon. High protein requirements."
        },
        {
            "id": "P003",
            "name": "Robert Johnson",
            "age": 58,
            "weight": 88.0,
            "height": 180.0,
            "dietaryRestrictions": ["low-sodium", "heart-healthy"],
            "allergies": [],
            "medicalConditions": ["coronary artery disease", "high cholesterol"],
            "calorieTarget": 1900,
            "notes": "Cardiac rehabilitation patient. Avoid saturated fats."
        }
    ]

    return patients[:count]

#2. create json file for patient information
def save_patients_to_json(patients: List[Dict[str, Any]], output_file: str) -> None:
    """
    Save patient data to a JSON file.

    Args:
        patients: List of patient dictionaries
        output_file: Path to the output JSON file
    """
    data = {
        "patients": patients,
        "metadata": {
            "total_count": len(patients),
            "generated_at": datetime.now().isoformat(),
            "schema_version": "1.0"
        }
    }

    with open(output_file, 'w') as f:
        json.dump(data, f, indent=2)

    print(f"✓ Successfully saved {len(patients)} patients to {output_file}")


def main():
    """Main function to demonstrate usage."""
    # Extract schema from TypeScript file
    typescript_file = '/mnt/user-data/uploads/types.ts'

    try:
        schema = extract_patient_schema(typescript_file)
        print("Patient Schema Extracted:")
        print(json.dumps(schema, indent=2))
        print()
    except Exception as e:
        print(f"Error extracting schema: {e}")

    # Create sample patients
    patients = create_multiple_patients(3)

    # Save to JSON file
    output_file = '/mnt/user-data/outputs/patients.json'
    save_patients_to_json(patients, output_file)

    # Also create a single patient example
    single_patient = create_sample_patient("P004")
    single_output = '/mnt/user-data/outputs/single_patient.json'

    with open(single_output, 'w') as f:
        json.dump(single_patient, f, indent=2)

if __name__ == "__main__":
    main()

#3. pass json file to llm

#4. receive meal plan and aggregate daily procurement
def extract_daily_meal_plans(meal_plan_data: Dict[str, Any]) -> List[Dict[str, Any]]:
    """
    Extract all meal plan information for each day.

    Args:
        meal_plan_data: Dictionary containing the complete meal plan JSON data

    Returns:
        List of dictionaries, each containing a day's complete meal information
    """
    try:
        days_data = meal_plan_data['meal_plan']['days']

        extracted_days = []
        for day in days_data:
            day_info = {
                'day_number': day['day'],
                'meals': day['meals'],
                'daily_total_calories': day['daily_total_calories'],
                'meal_count': len(day['meals'])
            }
            extracted_days.append(day_info)

        return extracted_days

    except KeyError as e:
        raise KeyError(f"Missing expected key in meal plan data: {e}")


def extract_weekly_procurement(meal_plan_data: Dict[str, Any]) -> Dict[str, Any]:
    """
    Extract all weekly procurement information including shopping list.

    Args:
        meal_plan_data: Dictionary containing the complete meal plan JSON data

    Returns:
        Dictionary containing shopping list and procurement metadata
    """
    try:
        procurement_data = meal_plan_data['weekly_procurement']

        extracted_procurement = {
            'shopping_list': procurement_data['shopping_list'],
            'total_ingredients': procurement_data['total_ingredients'],
            'aggregation_note': procurement_data['aggregation_note'],
            'ingredient_count': len(procurement_data['shopping_list'])
        }

        return extracted_procurement

    except KeyError as e:
        raise KeyError(f"Missing expected key in procurement data: {e}")


# Example usage
if __name__ == "__main__":
    # Load your JSON data
    with open('meal_plan_Patient_1_Heart_Disease_+_Diabetes_+_Lactose_Intolerant.json', 'r') as f:
        data = json.load(f)

    # Extract daily meal plans
    daily_plans = extract_daily_meal_plans(data)
    print("=== DAILY MEAL PLANS ===")
    for day in daily_plans:
        print(f"\nDay {day['day_number']}:")
        print(f"  Total Calories: {day['daily_total_calories']}")
        print(f"  Meals ({day['meal_count']}):")
        for meal in day['meals']:
            print(f"    - {meal['type']}: {meal['meal_name']} ({meal['calories']} cal)")

    # Extract weekly procurement
    procurement = extract_weekly_procurement(data)
    print("\n\n=== WEEKLY PROCUREMENT ===")
    print(f"Total Ingredients: {procurement['total_ingredients']}")
    print(f"Aggregation Note: {procurement['aggregation_note']}")
    print("\nShopping List:")
    for item, quantity in procurement['shopping_list'].items():
        print(f"  - {item}: {quantity}")

#5. pass back patient meal plan for 7 days
#6. pass back daily procurement at the very end